// <auto-generated />
using System;
using FinanceAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260326202513_SeedCategories")]
    partial class SeedCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Finance_API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alimentação",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Transporte",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Salário",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Investimentos",
                            Type = 3
                        },
                        new
                        {
                            Id = 5,
                            Name = "Lazer",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Moradia",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Saúde",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Educação",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "Assinaturas",
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            Name = "Compras",
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            Name = "Freelance",
                            Type = 0
                        },
                        new
                        {
                            Id = 13,
                            Name = "Dividendos",
                            Type = 3
                        },
                        new
                        {
                            Id = 14,
                            Name = "Rendimentos",
                            Type = 3
                        },
                        new
                        {
                            Id = 15,
                            Name = "Outros",
                            Type = 1
                        });
                });

            modelBuilder.Entity("Finance_API.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Finance_API.Models.Transaction", b =>
                {
                    b.HasOne("Finance_API.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Finance_API.Models.Category", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
